version: "3.3"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  migrate:
    build: .
    image: eanagnostopoulou/naiades-city-web
    command: python manage.py migrate --noinput
    environment:
        - DATABASE_HOST=db
        - DATABASE_NAME=postgres
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=postgres
        - NAIADES_API=https://dashboard-naiades-dev.herokuapp.com/api
    depends_on:
      - db
  web:
    build: .
    image: eanagnostopoulou/naiades-city-web
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "${NAIADES_CITY_PORT:-80}:8000"
    environment:
        - DATABASE_HOST=db
        - DATABASE_NAME=postgres
        - DATABASE_USER=postgres
        - DATABASE_PASSWORD=postgres
        - NAIADES_API=https://dashboard-naiades-dev.herokuapp.com/api
    depends_on:
      - db
      - migrate